language: node_js
dist: trusty
sudo: required

notifications:
  email: false

services:
  - postgresql

node_js:
  - "6"
  - "6.1"
env:
  - TEST_DATABASE_URL=postgres://postgres@localhost:5432/pokedom_test

before_script:
  - psql -c 'create database pokedom_test;' -U postgres

script:
  - npm run migration:migrate:test
  - npm test -- -u --forceExit --verbose
  - npm run lint
